import { describe, it, expect } from 'vitest';
import { isBinaryFile, isGeneratedFile } from '../../src/utils/file-heuristics.js';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

describe('file-heuristics', () => {
  describe('isBinaryFile', () => {
    it('returns true for non-existent files (fails safe)', () => {
      expect(isBinaryFile('/does/not/exist.txt')).toBe(true);
    });

    it('returns false for normal text files', () => {
      const tmpFile = path.join(os.tmpdir(), 'test-text.txt');
      fs.writeFileSync(tmpFile, 'hello world\nthis is text\n');
      expect(isBinaryFile(tmpFile)).toBe(false);
      fs.rmSync(tmpFile, { force: true });
    });

    it('returns true for files containing null bytes in the first 8KB', () => {
      const tmpFile = path.join(os.tmpdir(), 'test-binary.bin');
      const buf = Buffer.alloc(8192);
      buf.fill(0); // fill with null bytes
      fs.writeFileSync(tmpFile, buf);
      expect(isBinaryFile(tmpFile)).toBe(true);
      fs.rmSync(tmpFile, { force: true });
    });
  });

  describe('isGeneratedFile', () => {
    it('returns true for common lockfiles', () => {
      expect(isGeneratedFile('package-lock.json', '{}')).toBe(true);
      expect(isGeneratedFile('yarn.lock', '')).toBe(true);
      expect(isGeneratedFile('pnpm-lock.yaml', '')).toBe(true);
      expect(isGeneratedFile('Cargo.lock', '')).toBe(true);
    });

    it('returns true for minified javascript (very long lines)', () => {
      const longLine = 'a'.repeat(600);
      expect(isGeneratedFile('script.min.js', longLine)).toBe(true);

      // Even without .min.js, it should detect based on average line length > 500
      expect(isGeneratedFile('script.js', longLine)).toBe(true);
    });

    it('returns true for generated headers', () => {
      expect(isGeneratedFile('foo.ts', '// @generated by some tool\nconst a = 1;')).toBe(true);
      expect(isGeneratedFile('bar.ts', '/* eslint-disable */\nconsole.log(1);')).toBe(true);
      expect(isGeneratedFile('baz.ts', '// auto-generated file\nlet x = 2;')).toBe(true);
    });

    it('returns false for normal code files', () => {
      const code = `
        function foo() {
          return 'bar';
        }
      `;
      expect(isGeneratedFile('normal.ts', code)).toBe(false);
    });
  });
});
